import Foundation

// swiftlint:disable type_body_length

struct SampleImgurJSON {
    let payload: [String: Any] = {
        return [
            "success": 1,
            "status": 200,
            "data": [
                [
                    "id": "aWOd4wx",
                    "title": "ready for a walk",
                    "description": nil,
                    "datetime": 1687057114,
                    "cover": "QTO5Cwj",
                    "cover_width": 1566,
                    "cover_height": 2048,
                    "account_url": "nimh88",
                    "account_id": 171514145,
                    "privacy": "hidden",
                    "layout": "blog",
                    "views": 2073,
                    "link": "https://imgur.com/a/aWOd4wx",
                    "ups": 32,
                    "downs": 1,
                    "points": 31,
                    "score": 31,
                    "is_album": true,
                    "vote": nil,
                    "favorite": false,
                    "nsfw": false,
                    "section": "",
                    "comment_count": 2,
                    "favorite_count": 1,
                    "topic": nil,
                    "topic_id": nil,
                    "images_count": 1,
                    "in_gallery": true,
                    "is_ad": false,
                    "tags": [
                        [
                            "name": "dog",
                            "display_name": "dog",
                            "followers": 2424227,
                            "total_items": 222464,
                            "following": false,
                            "is_whitelisted": false,
                            "background_hash": "59NSmVP",
                            "thumbnail_hash": nil,
                            "accent": "008261",
                            "background_is_animated": false,
                            "thumbnail_is_animated": false,
                            "is_promoted": false,
                            "description": "human's best friend",
                            "logo_hash": nil,
                            "logo_destination_url": nil,
                            "description_annotations": [:]
                        ],
                        [
                            "name": "chihuahua",
                            "display_name": "chihuahua",
                            "followers": 1134,
                            "total_items": 2645,
                            "following": false,
                            "is_whitelisted": false,
                            "background_hash": "R1dEESs",
                            "thumbnail_hash": nil,
                            "accent": "5E58CB",
                            "background_is_animated": false,
                            "thumbnail_is_animated": false,
                            "is_promoted": false,
                            "description": "",
                            "logo_hash": nil,
                            "logo_destination_url": nil,
                            "description_annotations": []
                        ]
                    ],
                    "ad_type": 0,
                    "ad_url": "",
                    "in_most_viral": false,
                    "include_album_ads": false,
                    "images": [
                        [
                            "id": "QTO5Cwj",
                            "title": nil,
                            "description": "#dog #chihuahua",
                            "datetime": 1687057037,
                            "type": "image/jpeg",
                            "animated": false,
                            "width": 1566,
                            "height": 2048,
                            "size": 344468,
                            "views": 313,
                            "bandwidth": 107818484,
                            "vote": nil,
                            "favorite": false,
                            "nsfw": nil,
                            "section": nil,
                            "account_url": nil,
                            "account_id": nil,
                            "is_ad": false,
                            "in_most_viral": false,
                            "has_sound": false,
                            "tags": [],
                            "ad_type": 0,
                            "ad_url": "",
                            "edited": "0",
                            "in_gallery": false,
                            "link": "https://i.imgur.com/QTO5Cwj.jpg",
                            "comment_count": nil,
                            "favorite_count": nil,
                            "ups": nil,
                            "downs": nil,
                            "points": nil,
                            "score": nil
                        ]
                    ],
                    "ad_config": [
                        "safeFlags": [
                            "album",
                            "in_gallery",
                            "sixth_mod_safe",
                            "gallery"
                        ],
                        "highRiskFlags": [],
                        "unsafeFlags": [],
                        "wallUnsafeFlags": [],
                        "showsAds": true,
                        "showAdLevel": 2,
                        "safe_flags": [
                            "album",
                            "in_gallery",
                            "sixth_mod_safe",
                            "gallery"
                        ],
                        "high_risk_flags": [],
                        "unsafe_flags": [],
                        "wall_unsafe_flags": [],
                        "show_ads": true,
                        "show_ad_level": 2,
                        "nsfw_score": 0
                    ]
                ],
                [
                    "id": "q11AuWA",
                    "title": "carnitas sub: carnitas, spicy sour cream, pico de gallo and melted chihuahua cheese",
                    "description": nil,
                    "datetime": 1686258497,
                    "cover": "yNYynjD",
                    "cover_width": 2048,
                    "cover_height": 1312,
                    "account_url": "understandablyscared",
                    "account_id": 171438917,
                    "privacy": "hidden",
                    "layout": "blog",
                    "views": 4256,
                    "link": "https://imgur.com/a/q11AuWA",
                    "ups": 87,
                    "downs": 6,
                    "points": 81,
                    "score": 83,
                    "is_album": true,
                    "vote": nil,
                    "favorite": false,
                    "nsfw": false,
                    "section": "",
                    "comment_count": 24,
                    "favorite_count": 4,
                    "topic": nil,
                    "topic_id": nil,
                    "images_count": 5,
                    "in_gallery": true,
                    "is_ad": false,
                    "tags": [
                        [
                            "name": "food_porn",
                            "display_name": "food porn",
                            "followers": 42351,
                            "total_items": 33989,
                            "following": false,
                            "is_whitelisted": false,
                            "background_hash": "eyOzDXP",
                            "thumbnail_hash": "eyOzDXP",
                            "accent": "B1273C",
                            "background_is_animated": false,
                            "thumbnail_is_animated": false,
                            "is_promoted": false,
                            "description": "",
                            "logo_hash": nil,
                            "logo_destination_url": nil,
                            "description_annotations": [:]
                        ],
                        [
                            "name": "sandwich",
                            "display_name": "sandwich",
                            "followers": 755,
                            "total_items": 1568,
                            "following": false,
                            "is_whitelisted": false,
                            "background_hash": "v2L4vnj",
                            "thumbnail_hash": nil,
                            "accent": "24565E",
                            "background_is_animated": false,
                            "thumbnail_is_animated": false,
                            "is_promoted": false,
                            "description": "",
                            "logo_hash": nil,
                            "logo_destination_url": nil,
                            "description_annotations": [:]
                        ],
                        [
                            "name": "food",
                            "display_name": "Food",
                            "followers": 81834,
                            "total_items": 76163,
                            "following": false,
                            "is_whitelisted": false,
                            "background_hash": "cqJ1tS4",
                            "thumbnail_hash": nil,
                            "accent": "2EA799",
                            "background_is_animated": false,
                            "thumbnail_is_animated": false,
                            "is_promoted": false,
                            "description": "",
                            "logo_hash": nil,
                            "logo_destination_url": nil,
                            "description_annotations": [:]
                        ]
                    ],
                    "ad_type": 0,
                    "ad_url": "",
                    "in_most_viral": false,
                    "include_album_ads": false,
                    "images": [
                        [
                            "id": "yNYynjD",
                            "title": nil,
                            "description": nil,
                            "datetime": 1686258237,
                            "type": "image/jpeg",
                            "animated": false,
                            "width": 2048,
                            "height": 1312,
                            "size": 478939,
                            "views": 450,
                            "bandwidth": 215522550,
                            "vote": nil,
                            "favorite": false,
                            "nsfw": nil,
                            "section": nil,
                            "account_url": nil,
                            "account_id": nil,
                            "is_ad": false,
                            "in_most_viral": false,
                            "has_sound": false,
                            "tags": [],
                            "ad_type": 0,
                            "ad_url": "",
                            "edited": "0",
                            "in_gallery": false,
                            "link": "https://i.imgur.com/yNYynjD.jpg",
                            "comment_count": nil,
                            "favorite_count": nil,
                            "ups": nil,
                            "downs": nil,
                            "points": nil,
                            "score": nil
                        ],
                        [
                            "id": "OjODf3h",
                            "title": nil,
                            "description": nil,
                            "datetime": 1686258261,
                            "type": "image/jpeg",
                            "animated": false,
                            "width": 1536,
                            "height": 2048,
                            "size": 334187,
                            "views": 451,
                            "bandwidth": 150718337,
                            "vote": nil,
                            "favorite": false,
                            "nsfw": nil,
                            "section": nil,
                            "account_url": nil,
                            "account_id": nil,
                            "is_ad": false,
                            "in_most_viral": false,
                            "has_sound": false,
                            "tags": [],
                            "ad_type": 0,
                            "ad_url": "",
                            "edited": "0",
                            "in_gallery": false,
                            "link": "https://i.imgur.com/OjODf3h.jpg",
                            "comment_count": nil,
                            "favorite_count": nil,
                            "ups": nil,
                            "downs": nil,
                            "points": nil,
                            "score": nil
                        ],
                        [
                            "id": "HCrgSx4",
                            "title": nil,
                            "description": "i added a little more after tasting",
                            "datetime": 1686258243,
                            "type": "image/jpeg",
                            "animated": false,
                            "width": 1536,
                            "height": 2048,
                            "size": 308963,
                            "views": 270,
                            "bandwidth": 83420010,
                            "vote": nil,
                            "favorite": false,
                            "nsfw": nil,
                            "section": nil,
                            "account_url": nil,
                            "account_id": nil,
                            "is_ad": false,
                            "in_most_viral": false,
                            "has_sound": false,
                            "tags": [],
                            "ad_type": 0,
                            "ad_url": "",
                            "edited": "0",
                            "in_gallery": false,
                            "link": "https://i.imgur.com/HCrgSx4.jpg",
                            "comment_count": nil,
                            "favorite_count": nil,
                            "ups": nil,
                            "downs": nil,
                            "points": nil,
                            "score": nil
                        ]
                    ],
                    "ad_config": [
                        "safeFlags": [
                            "album",
                            "in_gallery",
                            "sixth_mod_safe",
                            "gallery"
                        ],
                        "highRiskFlags": [],
                        "unsafeFlags": [],
                        "wallUnsafeFlags": [],
                        "showsAds": true,
                        "showAdLevel": 2,
                        "safe_flags": [
                            "album",
                            "in_gallery",
                            "sixth_mod_safe",
                            "gallery"
                        ],
                        "high_risk_flags": [],
                        "unsafe_flags": [],
                        "wall_unsafe_flags": [],
                        "show_ads": true,
                        "show_ad_level": 2,
                        "nsfw_score": 0
                    ]
                ]
            ]
        ]
    }()
}

// swiftlint:enable type_body_length
