source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "16.0"
use_frameworks!
inhibit_all_warnings!

target "Hyperloop" do
  pod "SDWebImage", "5.16.0"

  pod "SwiftLint", "0.50.3"
end

target "Specs" do
  pod "Quick", "7.0.2"
  pod "Nimble", "12.0.1"
end
