source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.2'
use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'Capsule', '0.2.4'
end

target :AsyncImageFetcherDemo do
  shared_pods

  pod 'SwiftLint', '0.39.1'
end

target :Specs do
  shared_pods

  pod 'Quick', '2.2.0'
  pod 'Nimble', '8.0.5'
end
