default_platform(:ios)

platform :ios do

  desc "Run specs"
  lane :specs do
    scan(scheme: "Cuadrado",
         clean: true,
         configuration: "Debug",
         output_style: "rspec")
  end

end
